# "Skript" Propra 1 und 2

## Bauen

Voraussetzungen: docker 

Dockerimage erzeugen: `make dockerimage`
Buch erzeugen: `make`

Der Buildprozess verwendet das Dockerimage. 

<<<<<<< Updated upstream
 
=======
## Inhalte
Die Themen, die ich in der `master.adoc` Datei aufgeschrieben habe, sind noch nicht wirklich sortiert und vollständig und sollen nur als Startpunkt dienen. Es können gerne Themen hinzugefügt, geändert und in andere Reihenfolge gebbracht werden.

## Vorgehen

### Schreiben
. Wählt ein Thema. Falls das aus der Übersicht stammt, löscht es dort und fügt eine Datei im Ordner Chapter mit dem Thema hinzu.
. Fügt die Datei als include in die `master.adoc` ein.
. Formuliert das Thema aus.
. Legt ein Github Issue an. Der Titel sollte der Dateiname sein und es soll mit dem review Label getaggt werden.  

### Review
Jedes Thema soll mindestens von zwei von euch reviewt werden. Wenn euch der Sinn nach Reviewing steht (oder ihr seht, dass die Review Sektion sich füllt), schnappt euch ein Issue und fangt an. Fehler bitte sofort verbessern, falls etwas unklar ist, diskutiert das im Issue. Sollte es Fragen geben, könnt ihr Jens, Chris oder Christian im Ticket taggen. 
Wenn zwei Personen die Datei reviewt haben, schließt ihr bitte das Ticket. Lasst den Review Tag aber an dem Issue dran. 




>>>>>>> Stashed changes
